<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="../index.php">PoS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="../html/artigos.html">Criar Artigo</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="../html/lista_artigos.php">Lista de Artigos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="../app/logout.php">Logout</a>
                </li>
            </ul>
        </div>
    </div>
</nav>